displayName=Better Drift Net
author=vividflash
description=Improved Drift net fishing and misclick guards
tags=drift,net,driftnet,fossil,island,underwater,fishing,hunter,guard,misclick
plugins=com.vividflash.betterdriftnet.BetterDriftNetPlugin
build=standard
version=1.3
